#+title: Readme

Hi there!
How did you find this repo?
You either me and want to install belowed NixOS on new system or you are very lost and need to get back to normal Linux distribuions as fast as possible while you can, don't try to help, leave me here, now I can't return to normal people, it is too late.
If you are still here then lets discuss my setup.
* Setup
Currently I'm using nixos-unstable with flake based configuration.
As my primary maching is laptop - all links will be pointing to it.
I try to keep vm configs up to date, but as it is not used I rarely actually do it.

Installed packages
- Hyprland
  Is Wayland dynamic tiling compositor
  - [[file:machines/laptop/nixos-modules/hypr.nix][nixos configs]]
  - [[file:modules/rice/my/hypr/default.nix][home-manager]]
- Stylix
  Used to customize theming across system
  - [[file:machines/laptop/default.nix][nixos configs]] - search for stylix
  - [[file:machines/laptop/home.nix][home-manager]] - seach for stylix
- Alacritty
- Browsers
  There are some options that can be enabled using `dov.browser.{browserName} = true;`
  Available options:
  1. Firefox
  2. Qutebrowser
  3. Chrome
  4. Brave
  5. Vivaldi
- Filemanager
  I use ranger for terminal and thunar for GUI option


* Installation
1. Create installation flashdrive with latest iso using this command
  #+begin_src bash
  sudo dd bs=4M conv=fsync oflag=direct status=progress if=<path-to-image> of=/dev/sdX
  #+end_src
2. Create installation flashdrive with latest iso using this command
  #+begin_src bash
  sudo dd bs=4M conv=fsync oflag=direct status=progress if=<path-to-image> of=/dev/sdX
  #+end_src
3. Clone this repo
  #+begin_src bash
  git clone https://github.com/LichHunter/nixos-dotfiles
  #+end_src
4. Format disk
  #+begin_src bash
  sudo nix --experimental-features "nix-command flakes" run github:nix-community/disko/latest -- --mode destroy,format,mount ~/nixos-dotfiles/machines/laptop/disko-configuration.nix
  #+end_src
5. Mount disk
  #+begin_src bash
  sudo mount /dev/nvme0n1 /mnt
  #+end_src
6. Generate nixos configurations
  #+begin_src bash
  sudo nixos-generate-config --root /mnt
  #+end_src
7. Copy cloned config to '/mnt/etc/nixos'
  #+begin_src bash
  sudo cp -r * /mnt/etc/nixos
  #+end_src
8. Install nixos
  #+begin_src bash
  nixos-install --flake /mnt/etc/nixos#laptop
  #+end_src
** Post install
After you installed os you can install install:
*** Doom emacs
#+begin_src bash
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
#+end_src
* Afterword
There is also [[file:wiki.org][wiki.org]] file that contains some commands that can be used

* TODO
- add user password for laptop config
