keys:
  - &primary age19wvqtn4ju6k4vs8fxr34unl6xx4cv04jw0lx9ps20xlde927zfssgl4qke
  - &uzume age1ka8dtunrjhvrnugegd4hfzxnctcvrevrpyr96pymn3arw6dvh3hs58azmu
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *primary
          - *uzume
